export const environment = {
    production: true,
    apiUrl: 'http://clientged:8080/documaniacourrier/api/v1',
    basicUrl: 'http://clientged:8080/documaniacourrier',
    depart: 'dep',
    arrive: 'arr',
    editorPrefix:'doc',
    interne: 'Courrier interne',
    supportedMimeTypes:
    'application/vnd.oasis.opendocument.text application/vnd.oasis.opendocument.text-flat-xml application/vnd.oasis.opendocument.text-template application/vnd.oasis.opendocument.presentation application/vnd.oasis.opendocument.presentation-flat-xml application/vnd.oasis.opendocument.presentation-template application/vnd.oasis.opendocument.spreadsheet application/vnd.oasis.opendocument.spreadsheet-flat-xml application/vnd.oasis.opendocument.spreadsheet-template application/pdf image/tiff image/gif image/apng image/bmp image/jpeg image/png',
    max :250,
    maxlong:1000,
    mode:'premise' ,
    min: 1,
    maxDate: '2070/07/25',
    validationTime:15,
    log:"Basic ZGVtby5hZG1pbjp1c2Vy",
    tentative: 10,
    showLang: false,
    hideCodeBar: true,
    hideCapture: false,
    espaceEmetteurShow: false,
    documentIconShow: false,
    hideAchivage: false,
    hideArchive: true,
    hidePassOublie: false,
    hideDocument: false,
    hideDocumentSearch: false,
    hideStatus: false,
    hideRefAuto: false,
    HideSuppPartage: false,
    hideDocCodeBar: false,
    hideFlux: false,
    liasonHide: true,
    liasonCourHide: true,
    liasonDocHide: false,
    hideToast: false,
    maxUpload: 500000000,
    hideDocumentAdd: true,
    hideArchivageRm: false,

    footer: "ACAPS"
  };
